name: Deploy to GitHub Pages

on:
  push:
    branches:
      - week9-10

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: Meng0159/fit5032-applied-library
          ref: week9-10

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Updated to a more recent version

      - name: Debug - List directory contents
        run: ls -la

      - name: Debug - Display package.json contents
        run: cat package.json

      - name: Install dependencies
        run: |
          npm install
          npm ls

      - name: Build
        run: npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: dist
